# Simple workflow for deploying static content to GitHub Pages
name: Copy source code and minify to GitHub Pages branch

on:
  push:
    branches: 
      - source
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Set up Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
      - name: Merge source into main
        run: |
          git checkout main
          git merge source --no-ff
      # - name: Minify HTML
      #   uses: docker://textadi/minifier-compressor-html-action:v2
      #   env:
      #     DIR: .
      #     PARAM_MINIFY_CSS: True
      #     PARAM_MINIFY_JS: True
      - name: Commit and push to main
        run: |
          git add .
          git commit -m "Update main from source and minify HTML"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
