# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: 
      - source
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Set up Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
      - name: Merge source into main
        run: |
          git checkout main
          git merge source --no-ff --commit -m "Update main from source"
      - name: Push to main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
